/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlEntradas;
import Modelo.ModeloEntradas;
import Utileria.Utilhora;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Andres Daraviña
 */
public class Entradas extends javax.swing.JDialog {

    /**
     * Creates new form Entradas
     */
    String nombre1,cedula;
    public Entradas(Menu sc,String nombre,String cedula) {
        super(sc,true);
        this.nombre1 = nombre;
        this.cedula = cedula;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigou = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        hor = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        temperatura = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cancelar1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        hora = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        fecha = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        carn = new javax.swing.JLabel();
        telefono = new javax.swing.JFormattedTextField();
        nombre = new javax.swing.JTextField();
        cor = new javax.swing.JLabel();
        carnet = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        programa = new javax.swing.JComboBox<>();
        grados = new javax.swing.JLabel();
        guardar1 = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cancelar2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        crear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrada de Usuario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Ingreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Codigo Encargado");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Documento Usuario");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 73, -1, -1));

        codigou.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(codigou, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 70, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Id");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 35, -1, -1));
        jLabel4.setText(nombre1);

        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/buscar.png"))); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 65, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 35, -1, -1));
        jLabel6.setText(cedula);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/univalleR.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 19, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nombre Encargado");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 35, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hor.setText("Hora:");
        jPanel3.add(hor, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 183, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Apellido");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 103, -1, -1));

        temperatura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 60, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nombre");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 62, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Fecha:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 143, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Cargo");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 62, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Programa");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 103, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Ciudad");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 225, -1, -1));

        cancelar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/eliminar.png"))); // NOI18N
        cancelar1.setText("Cancelar");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });
        jPanel3.add(cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));
        cancelar1.setEnabled(false);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Tipo Documento");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 21, -1, -1));

        try {
            hora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        hora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, -1));
        hora.setText(Utilhora.getinstance().getDateHour());
        hora.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Direccion");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 183, -1, -1));

        try {
            fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, -1));
        fecha.setText(Utilhora.getinstance().getDateFecha());
        fecha.setEditable(false);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Telefono");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 143, -1, -1));

        temp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        temp.setText("Temperatura");
        jPanel3.add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 21, -1, -1));

        cargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Administrativo", "Visitante" }));
        jPanel3.add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 120, -1));
        cargo.setEnabled(false);

        carn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carn.setText("Carnet");
        jPanel3.add(carn, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 183, -1, -1));
        carn.setVisible(false);

        try {
            telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 141, 160, -1));
        telefono.setEditable(false);

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 59, 160, -1));
        nombre.setEditable(false);

        cor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cor.setText("Correo");
        jPanel3.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 21, -1, -1));
        cor.setVisible(false);

        carnet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(carnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, -1));
        carnet.setVisible(true);

        correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 20, 120, -1));
        correo.setVisible(false);

        apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 100, 160, -1));
        apellido.setEditable(false);

        direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 182, 160, -1));
        direccion.setEditable(false);

        ciudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 223, 160, -1));
        ciudad.setEditable(false);

        programa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        programa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Ing Industrial", "Lic Historia", "Musica", "Psicologia", "Tec Electronica", "Tec Sitemas" }));
        jPanel3.add(programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 120, -1));
        programa.setEnabled(false);

        grados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        grados.setText("°C");
        jPanel3.add(grados, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        guardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/Ok-icon.png"))); // NOI18N
        guardar1.setText("Guardar");
        guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar1ActionPerformed(evt);
            }
        });
        jPanel3.add(guardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));
        guardar1.setEnabled(false);

        tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "C.C Extranjera", "T.I", "Pasaporte" }));
        jPanel3.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, -1));
        tipo.setEnabled(false);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -120, 600, 460));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 117, 537, 265));

        estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estado.setText("Estado");
        jPanel2.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 73, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, -1, 490));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 580, 410));

        cancelar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/back-icon.png"))); // NOI18N
        cancelar2.setText("Volver");
        cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar2ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 435, -1, -1));
        cancelar1.setEnabled(false);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/barrahorilarg.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 609, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/barrahorilarg.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 471, 609, -1));

        crear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/mas.png"))); // NOI18N
        crear.setText("Crear");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel1.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 433, -1, -1));
        crear.setVisible(false);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        
        try {
            ModeloEntradas me = new ModeloEntradas();
            me.setCedula(Long.parseLong(codigou.getText()));
            me.setFecha(fecha.getText());
            ControlEntradas ce = new ControlEntradas();
            ce.buscar(me);
            tipo.setSelectedItem(me.getTipodoc());
            nombre.setText(me.getNombre());
            apellido.setText(me.getApellido());
            telefono.setText(me.getTelefono());
            direccion.setText(me.getDireccion());
            ciudad.setText(me.getCiudad());
            cargo.setSelectedItem(me.getCargo());
            if(!me.getPrograma().equals("null")){
                programa.setSelectedItem(me.getPrograma());
            }else{
                programa.setSelectedItem("Ninguno");
            }
            guardar1.setEnabled(true);
            cancelar1.setEnabled(true);
        }catch (NumberFormatException ex1) {
            Dialogos dg = new Dialogos(null,"Debe ingresar un valor numerico","");
            dg.setVisible(true);
        }
        catch (Exception ex) {
            if(ex.getMessage().equals("El usuario no existe")){
                boolean aceptar = false;
                Mensaje ms = new Mensaje(null,"El usuario no existe.","Desea crear el usuario?");
                ms.setVisible(true);
                aceptar = ms.confirmar;
                if(aceptar==true){
                    programa.setEnabled(true);
                    crear.setVisible(true);
                    cancelar1.setEnabled(true);
                    tipo.setEnabled(true);
                    nombre.setEditable(true);
                    apellido.setEditable(true);
                    telefono.setEditable(true);
                    direccion.setEditable(true);
                    ciudad.setEditable(true);
                    cargo.setEnabled(true);
                    cor.setVisible(true);
                    correo.setVisible(true);
                    temp.setVisible(false);
                    temperatura.setVisible(false);
                    hor.setVisible(false);
                    hora.setVisible(false);
                    carn.setVisible(true);
                    carnet.setVisible(true);
                }
            }else{
                Dialogos dg = new Dialogos(null,ex.getMessage(),"");
                dg.setVisible(true);
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
          vaciar();
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar2ActionPerformed
        dispose();
    }//GEN-LAST:event_cancelar2ActionPerformed

    private void guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar1ActionPerformed
        ModeloEntradas me = new ModeloEntradas();
        try {
            if (Integer.parseInt(temperatura.getText()) < 37) {
                try {
                    me.setFecha(fecha.getText());
                    me.setHora(hora.getText());
                    me.setTemperatura(temperatura.getText());
                    me.setCedula(Long.parseLong(codigou.getText()));
                    me.setCedulafuncionario(Long.parseLong(jLabel4.getText()));
                    ControlEntradas ce = new ControlEntradas();
                ce.crearEntrada(me);
                    Dialogos dg = new Dialogos(null, "La entrada fue creada exitosamente", "");
                    dg.setVisible(true);
                    dispose();
                } catch (Exception e) {
                    Dialogos dg = new Dialogos(null, e.getMessage(), "");
                    dg.setVisible(true);
                }
            } else {
                Dialogos dg = new Dialogos(null, "Temperatura alta, se registrara", "una novedad");
                dg.setVisible(true);
                Novedad nv = new Novedad(null, codigou.getText(), nombre.getText(), temperatura.getText(), jLabel4.getText());
                nv.setVisible(true);
                dispose();
            }
        } catch (NumberFormatException ex) {
            if(temperatura.getText().matches("\\d*")==false){
            Dialogos dg = new Dialogos(null, "La temperatura debe ser un valor", "numerico");
            dg.setVisible(true);
            }else{
            Dialogos dg = new Dialogos(null, "Por favor ingresar la temperatura", "");
            dg.setVisible(true);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_guardar1ActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        try {
            ModeloEntradas me = new ModeloEntradas();
            me.setCedula(Long.parseLong(codigou.getText()));
            me.setTipodoc(""+tipo.getSelectedItem());
            me.setNombre(nombre.getText());
            me.setApellido(apellido.getText());
            me.setTelefono(telefono.getText());
            me.setDireccion(direccion.getText());
            me.setCiudad(ciudad.getText());
            me.setCargo(""+cargo.getSelectedItem());
            me.setPrograma(""+programa.getSelectedItem());
            me.setCorreo(correo.getText());
            me.setCarnet(carnet.getText());
            ControlEntradas ce = new ControlEntradas();
            ce.crearUsuario(me);
            Dialogos d = new Dialogos(null,"Usuario creado exitosamente","");
            d.setVisible(true);
            vaciar();
        } catch (Exception e) {
            Dialogos d = new Dialogos(null,e.getMessage(),"");
            d.setVisible(true);
        }
        
    }//GEN-LAST:event_crearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JButton cancelar2;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JLabel carn;
    private javax.swing.JTextField carnet;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField codigou;
    private javax.swing.JLabel cor;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crear;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel estado;
    private javax.swing.JFormattedTextField fecha;
    private javax.swing.JLabel grados;
    private javax.swing.JButton guardar1;
    private javax.swing.JLabel hor;
    private javax.swing.JFormattedTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> programa;
    private javax.swing.JFormattedTextField telefono;
    private javax.swing.JLabel temp;
    private javax.swing.JTextField temperatura;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables

    private void vaciar() {
        crear.setVisible(false);
                    cancelar1.setEnabled(false);
                    tipo.setEnabled(false);
                    nombre.setEditable(false);
                    apellido.setEditable(false);
                    telefono.setEditable(false);
                    direccion.setEditable(false);
                    ciudad.setEditable(false);
                    cargo.setEnabled(false);
                    programa.setEnabled(false);
                    cor.setVisible(false);
                    correo.setVisible(false);
                    temp.setVisible(true);
                    temperatura.setVisible(true);
        tipo.setSelectedItem("CC");
        nombre.setText("");
        apellido.setText("");
        telefono.setText("");
        direccion.setText("");
        ciudad.setText("");
        cargo.setSelectedItem("Estudiante");
        programa.setSelectedItem("Ninguno");
        codigou.setText("");
        codigou.requestFocus();
        guardar1.setEnabled(false);
        cancelar1.setEnabled(false);
        crear.setVisible(false);
        hor.setVisible(true);
        hora.setVisible(true);
        carn.setVisible(false);
        carnet.setVisible(false);
    }

}
