package Vista;

import Controlador.ControlLogeo;
import Modelo.ModeloLogeo;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Logeo extends javax.swing.JDialog {
    
    public String nicknames = "",cedula = "",nombre = "";
    public boolean sesion = false;
    public Logeo(Menu sc) {
        super(sc,true);
        initComponents();
        keyEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        contraseña = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logeo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel.setText("Nickname");
        jPanel2.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 50, -1, -1));

        nickname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 47, 136, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 91, -1, -1));

        iniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/Ok-icon.png"))); // NOI18N
        iniciar.setText("Iniciar Sesion");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel2.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 129, -1, -1));

        volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/back-icon.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 129, -1, -1));

        contraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 88, 136, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -150, 470, 410));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 280, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -150, 470, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/barrahorizonta.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        
        try {
            ModeloLogeo ml = new ModeloLogeo();
            ml.setUsername(nickname.getText());
            ml.setContraseña(contraseña.getText());
            ControlLogeo cl = new ControlLogeo();
            cl.logeo(ml);
            Dialogos d = new Dialogos(null,"Logeo Exitoso","");
            new ProcessBuilder("cmd", "/c", "cls").inheritIO().start().waitFor();
            nicknames = nickname.getText();
            nombre = cl.nombre;
            cedula = cl.cedula;
            sesion = true;
            d.setVisible(true);
            dispose();
            
        } catch (Exception ex) {
            Dialogos d = new Dialogos(null,ex.getMessage(),"");
            d.setVisible(true);
        }
    }//GEN-LAST:event_iniciarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField nickname;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
    private void keyEvents() {
    
        nickname.addKeyListener(new KeyListener() {
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_UP) {
                }
                if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    contraseña.requestFocus();
                }
                if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                }
                if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                }
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    contraseña.requestFocus();
                }
            }

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent e) {
            }
        });
        
        contraseña.addKeyListener(new KeyListener() {
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_UP) {
                    nickname.requestFocus();
                }
                if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                    iniciar.requestFocus();
                }
                if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                }
                if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                }
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    iniciar.requestFocus();
                }
            }

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent e) {
            }
        });
        
        iniciar.addKeyListener(new KeyListener() {
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_UP) {
                    contraseña.requestFocus();
                }
                if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                }
                if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                    volver.requestFocus();
                }
                if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                }
            }

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent e) {
            }
        });
        
        volver.addKeyListener(new KeyListener() {
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_UP) {
                    contraseña.requestFocus();
                }
                if (e.getKeyCode() == KeyEvent.VK_DOWN) {
                }
                if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                }
                if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                    iniciar.requestFocus();
                }
            }

            public void keyTyped(KeyEvent e) {
            }

            public void keyPressed(KeyEvent e) {
            }
        });
        
    
    }
}
