/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControlNovedad;
import Modelo.ModeloNovedad;
import java.util.Properties;
import javax.mail.Session;

/**
 *
 * @author Andres Daraviña
 */
public class Novedad extends javax.swing.JDialog {
    int contadorap;
    String cedulafun;
    /** Creates new form Novedad */
    Novedad(Menu mn, String cedula, String nombre, String temperatura,String cedulafun) {
        super(mn,true);
        initComponents();
        nombreus.setText(nombre);
        codigou.setText(cedula);
        this.temperatura.setText(temperatura);
        this.cedulafun = cedulafun;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codigou = new javax.swing.JTextField();
        nombreus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enfermedad = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        enfermedades = new javax.swing.JTextField();
        temperatura = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        ultimosi = new javax.swing.JTextField();
        mas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        guardar1 = new javax.swing.JButton();
        enferm = new javax.swing.JComboBox<>();
        convive = new javax.swing.JComboBox<>();
        cancelar2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/eliminar.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novedad");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Novedad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Usuairo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        codigou.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigouActionPerformed(evt);
            }
        });
        jPanel2.add(codigou, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, -1));
        codigou.setEditable(false);

        nombreus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombreus.setText("Nombre");
        jPanel2.add(nombreus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Documento Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        enfermedad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enfermedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel2.add(enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -30, 490, 490));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        enfermedades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        temperatura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Enfermedades");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Ultimo Sitio Visitado");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Convive con Menores?");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Temperatura");

        ultimosi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        mas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mas.setText("+");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        jLabel3.setText("°");

        guardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/Ok-icon.png"))); // NOI18N
        guardar1.setText("Guardar");
        guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar1ActionPerformed(evt);
            }
        });

        enferm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        enferm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermActionPerformed(evt);
            }
        });

        convive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        convive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enferm, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ultimosi))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                        .addComponent(convive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mas))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(guardar1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel3)
                    .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(mas)
                    .addComponent(enfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(enferm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(convive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(ultimosi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardar1)
                .addContainerGap())
        );

        temperatura.setEditable(false);
        enferm.setVisible(false);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 265));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 380, 410));

        cancelar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/back-icon.png"))); // NOI18N
        cancelar2.setText("Volver");
        cancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar2ActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));
        cancelar.setEnabled(false);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/fondo1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 520, 490));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/barrahorilarg.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 609, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGS/barrahorilarg.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 471, 609, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar2ActionPerformed
        dispose();
    }//GEN-LAST:event_cancelar2ActionPerformed

    private void guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar1ActionPerformed
        
        try {
            String enfermedade="";
        
            for (int i = 0; i < enferm.getItemCount(); i++) {
                enfermedade = enfermedade+enferm.getItemAt(i)+",";
            }
            if(!"".equals(enfermedades.getText())){
                enfermedade = enfermedade+enfermedades.getText();
            }else{
                enfermedade = enfermedade.substring(0, enfermedade.length()-1);
            }
            ModeloNovedad mn = new ModeloNovedad();
            mn.setDocumento(codigou.getText());
            mn.setTemperatura(temperatura.getText());
            mn.setEnfermedades(enfermedade);
            mn.setConviveme(""+convive.getSelectedItem());
            mn.setUltimositio(ultimosi.getText());
            mn.setCedulafunc(cedulafun);
            ControlNovedad cn = new ControlNovedad();
            cn.crearNovedad(mn);           
            Dialogos d = new Dialogos(null,"Novedad creada exitosanente","");
            d.setVisible(true);
            dispose();
            
        } catch (Exception e) {
            Dialogos d = new Dialogos(null,e.getMessage(),"");
            d.setVisible(true);
        }
        
    }//GEN-LAST:event_guardar1ActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
 
        if (!enfermedades.getText().equals("")) {
            enferm.setVisible(true);
            if (enferm.getItemCount() != 0) {
                boolean esta = false;
                for (int i = 0; i < enferm.getItemCount(); i++) {
                    if (enferm.getItemAt(i).equals(enfermedades.getText())) {
                        Dialogos d = new Dialogos(null, "La enfermedad ya se encuentra", "registrada en esta novedad");
                        d.setVisible(true);
                        esta = true;
                    }
                }
                if (esta == false) {
                    enferm.addItem(enfermedades.getText());
                    enfermedades.setText("");
                }
            } else {
                enferm.addItem(enfermedades.getText());
                enfermedades.setText("");
            }
        }else{
            Dialogos d = new Dialogos(null, "Por favor ingrese una enfermedad", "");
            d.setVisible(true);
        }
        
        
        
        
    }//GEN-LAST:event_masActionPerformed

    private void codigouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigouActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void enfermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermActionPerformed

         if(enfermedades.getText().equals("")){

                enfermedades.setText(""+enferm.getSelectedItem());

                if (contadorap >= 0){
                    enferm.removeItem(enferm.getSelectedItem());
                    if(enferm.getItemCount()==0){
                        enferm.setVisible(false);
                    }
                }
                contadorap++;
            }
        
    }//GEN-LAST:event_enfermActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar2;
    private javax.swing.JTextField codigou;
    private javax.swing.JComboBox<String> convive;
    private javax.swing.JComboBox<String> enferm;
    private javax.swing.JLabel enfermedad;
    private javax.swing.JTextField enfermedades;
    private javax.swing.JButton guardar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mas;
    private javax.swing.JLabel nombreus;
    private javax.swing.JTextField temperatura;
    private javax.swing.JTextField ultimosi;
    // End of variables declaration//GEN-END:variables

}
